# Generated by Django 3.0.2 on 2020-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=70)),
                ('product_id', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
    ]
